xcodeproj 'Roomie.xcodeproj'
pod 'AFNetworking', '~> 1.3.0'
pod 'UIColor-Utilities', '~> 1.0.1'
pod 'CupertinoYankee', '~> 0.1.1'
pod 'MACalendarUI', :git => 'https://github.com/matt-holden/calendar-ui.git'
